name: Test and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm test -- --coverage

      - name: Upload coverage reports (optional)
        if: ${{ hashFiles('coverage/**') != '' }}
        uses: codecov/codecov-action@v5
        with:
          directory: ./coverage

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # ✅ Proper Pages configuration
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      # ✅ Upload site files (your `views/` folder contains index.html)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './views'

      # ✅ Correct deploy action (typo fixed)
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
